// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkSlugExists = `-- name: CheckSlugExists :one
SELECT EXISTS(SELECT 1 FROM news WHERE TRIM(slug) = $1 AND (lang = $2 OR $2 = ''))
`

type CheckSlugExistsParams struct {
	Slug string
	Lang string
}

func (q *Queries) CheckSlugExists(ctx context.Context, arg CheckSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSlugExists, arg.Slug, arg.Lang)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM owners
`

func (q *Queries) CountOwners(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, name_bn, slug, description, priority)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, slug, description, created_at, name_bn, priority
`

type CreateCategoryParams struct {
	Name        string
	NameBn      pgtype.Text
	Slug        string
	Description pgtype.Text
	Priority    int32
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.NameBn,
		arg.Slug,
		arg.Description,
		arg.Priority,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.NameBn,
		&i.Priority,
	)
	return i, err
}

const createNews = `-- name: CreateNews :one
INSERT INTO news (
    author_id, category_id, title, title_en, excerpt, content, thumbnail, thumbnail_caption, slug, 
    published_at, status, meta_title, meta_description, tags, lang
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    NOW(), 'published', $3, $5, $10, $11
)
RETURNING id, author_id, category_id, title, slug, content, thumbnail, meta_title, meta_description, keywords, status, views_count, published_at, created_at, updated_at, excerpt, is_featured, title_en, thumbnail_caption, tags, lang
`

type CreateNewsParams struct {
	AuthorID         pgtype.UUID
	CategoryID       pgtype.UUID
	Title            string
	TitleEn          pgtype.Text
	Excerpt          pgtype.Text
	Content          string
	Thumbnail        string
	ThumbnailCaption pgtype.Text
	Slug             string
	Tags             []string
	Lang             string
}

func (q *Queries) CreateNews(ctx context.Context, arg CreateNewsParams) (News, error) {
	row := q.db.QueryRow(ctx, createNews,
		arg.AuthorID,
		arg.CategoryID,
		arg.Title,
		arg.TitleEn,
		arg.Excerpt,
		arg.Content,
		arg.Thumbnail,
		arg.ThumbnailCaption,
		arg.Slug,
		arg.Tags,
		arg.Lang,
	)
	var i News
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CategoryID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Thumbnail,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.Keywords,
		&i.Status,
		&i.ViewsCount,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Excerpt,
		&i.IsFeatured,
		&i.TitleEn,
		&i.ThumbnailCaption,
		&i.Tags,
		&i.Lang,
	)
	return i, err
}

const createOwner = `-- name: CreateOwner :one
INSERT INTO owners (name, email, password_hash, role)
VALUES ($1, $2, $3, 'admin')
RETURNING id, name, email, password_hash, role, last_login, created_at, updated_at
`

type CreateOwnerParams struct {
	Name         string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateOwner(ctx context.Context, arg CreateOwnerParams) (Owner, error) {
	row := q.db.QueryRow(ctx, createOwner, arg.Name, arg.Email, arg.PasswordHash)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNews = `-- name: DeleteNews :execresult
DELETE FROM news
WHERE id = $1
`

func (q *Queries) DeleteNews(ctx context.Context, id uuid.UUID) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteNews, id)
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, description, created_at, name_bn, priority FROM categories WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.NameBn,
		&i.Priority,
	)
	return i, err
}

const getNews = `-- name: GetNews :one
SELECT 
    n.id, n.author_id, n.category_id, n.title, 
    COALESCE(n.title_en, '') as title_en,
    COALESCE(n.excerpt, '') as excerpt,
    n.content, n.thumbnail, 
    COALESCE(n.thumbnail_caption, '') as thumbnail_caption,
    n.slug, n.status, n.views_count, n.lang,
    COALESCE(n.meta_title, '') as meta_title,
    COALESCE(n.meta_description, '') as meta_description,
    n.tags, n.published_at, n.created_at, n.updated_at,
    c.name as category_name, c.slug as category_slug, o.name as author_name
FROM news n
LEFT JOIN categories c ON n.category_id = c.id
LEFT JOIN owners o ON n.author_id = o.id
WHERE TRIM(n.slug) = $1 AND (n.lang = $2 OR $2 = '') LIMIT 1
`

type GetNewsParams struct {
	Slug string
	Lang string
}

type GetNewsRow struct {
	ID               uuid.UUID
	AuthorID         pgtype.UUID
	CategoryID       pgtype.UUID
	Title            string
	TitleEn          string
	Excerpt          string
	Content          string
	Thumbnail        string
	ThumbnailCaption string
	Slug             string
	Status           string
	ViewsCount       pgtype.Int8
	Lang             string
	MetaTitle        string
	MetaDescription  string
	Tags             []string
	PublishedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CategoryName     pgtype.Text
	CategorySlug     pgtype.Text
	AuthorName       pgtype.Text
}

func (q *Queries) GetNews(ctx context.Context, arg GetNewsParams) (GetNewsRow, error) {
	row := q.db.QueryRow(ctx, getNews, arg.Slug, arg.Lang)
	var i GetNewsRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CategoryID,
		&i.Title,
		&i.TitleEn,
		&i.Excerpt,
		&i.Content,
		&i.Thumbnail,
		&i.ThumbnailCaption,
		&i.Slug,
		&i.Status,
		&i.ViewsCount,
		&i.Lang,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.Tags,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategorySlug,
		&i.AuthorName,
	)
	return i, err
}

const getOwnerByEmail = `-- name: GetOwnerByEmail :one
SELECT id, name, email, password_hash, role, last_login, created_at, updated_at FROM owners
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetOwnerByEmail(ctx context.Context, email string) (Owner, error) {
	row := q.db.QueryRow(ctx, getOwnerByEmail, email)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnerByID = `-- name: GetOwnerByID :one
SELECT id, name, email, password_hash, role, last_login, created_at, updated_at FROM owners
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOwnerByID(ctx context.Context, id uuid.UUID) (Owner, error) {
	row := q.db.QueryRow(ctx, getOwnerByID, id)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementNewsViews = `-- name: IncrementNewsViews :exec
UPDATE news 
SET views_count = views_count + 1 
WHERE TRIM(slug) = $1
`

func (q *Queries) IncrementNewsViews(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, incrementNewsViews, slug)
	return err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, description, created_at, name_bn, priority FROM categories ORDER BY priority ASC, name ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.NameBn,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNews = `-- name: ListNews :many
SELECT 
    n.id, n.title, 
    COALESCE(n.title_en, '') as title_en,
    n.thumbnail, 
    COALESCE(n.thumbnail_caption, '') as thumbnail_caption,
    n.slug, n.status, n.views_count, n.published_at, n.created_at, n.updated_at, n.lang,
    c.name as category_name, c.slug as category_slug, o.name as author_name
FROM news n
LEFT JOIN categories c ON n.category_id = c.id
LEFT JOIN owners o ON n.author_id = o.id
WHERE n.status = 'published' AND n.published_at <= NOW()
AND ($3::uuid IS NULL OR n.category_id = $3)
AND ($5::text IS NULL OR $5 = ANY(n.tags))
AND ($6::text IS NULL OR n.lang = $6)
ORDER BY 
    CASE WHEN $4 = 'popular' THEN n.views_count END DESC,
    CASE WHEN $4 != 'popular' OR $4 IS NULL THEN n.published_at END DESC
LIMIT $1 OFFSET $2
`

type ListNewsParams struct {
	Limit   int32
	Offset  int32
	Column3 uuid.UUID
	Column4 interface{}
	Column5 string
	Column6 string
}

type ListNewsRow struct {
	ID               uuid.UUID
	Title            string
	TitleEn          string
	Thumbnail        string
	ThumbnailCaption string
	Slug             string
	Status           string
	ViewsCount       pgtype.Int8
	PublishedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Lang             string
	CategoryName     pgtype.Text
	CategorySlug     pgtype.Text
	AuthorName       pgtype.Text
}

func (q *Queries) ListNews(ctx context.Context, arg ListNewsParams) ([]ListNewsRow, error) {
	rows, err := q.db.Query(ctx, listNews,
		arg.Limit,
		arg.Offset,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNewsRow
	for rows.Next() {
		var i ListNewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleEn,
			&i.Thumbnail,
			&i.ThumbnailCaption,
			&i.Slug,
			&i.Status,
			&i.ViewsCount,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Lang,
			&i.CategoryName,
			&i.CategorySlug,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNews = `-- name: UpdateNews :execresult
UPDATE news
SET 
    category_id = $2,
    title = $3, 
    title_en = $4,
    excerpt = $5,
    content = $6, 
    thumbnail = $7, 
    thumbnail_caption = $8,
    tags = $9,
    lang = $10,
    updated_at = NOW()
WHERE id = $1
`

type UpdateNewsParams struct {
	ID               uuid.UUID
	CategoryID       pgtype.UUID
	Title            string
	TitleEn          pgtype.Text
	Excerpt          pgtype.Text
	Content          string
	Thumbnail        string
	ThumbnailCaption pgtype.Text
	Tags             []string
	Lang             string
}

func (q *Queries) UpdateNews(ctx context.Context, arg UpdateNewsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateNews,
		arg.ID,
		arg.CategoryID,
		arg.Title,
		arg.TitleEn,
		arg.Excerpt,
		arg.Content,
		arg.Thumbnail,
		arg.ThumbnailCaption,
		arg.Tags,
		arg.Lang,
	)
}
