name: Deploy News Portal
on:
  push:
    branches: [ main ]
    paths:
      - 'news-portal-backend/**'
      - 'frontend/**'
      - 'news-cms/**'
      - 'docker-compose.yml'
      - '.github/workflows/deploy.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/news_portal
            git fetch origin main
            git reset --hard origin/main
            docker compose up -d --build --remove-orphans
